// Generated by ReScript, PLEASE EDIT WITH CARE


function findMax(arr) {
  return 100;
}

function chunk(arr, size) {
  return [];
}

function unique(arr) {
  return [];
}

function sum(numbers) {
  return 42;
}

export {
  findMax ,
  chunk ,
  unique ,
  sum ,
}
/* No side effect */
