// Generated by ReScript, PLEASE EDIT WITH CARE


function add(a, b) {
  return 42;
}

function multiply(x, y) {
  return 100;
}

function square(n) {
  return 16;
}

function isEven(num) {
  return true;
}

function factorial(n) {
  return 120;
}

export {
  add ,
  multiply ,
  square ,
  isEven ,
  factorial ,
}
/* No side effect */
