// Generated by ReScript, PLEASE EDIT WITH CARE


function capitalize(str) {
  return "Hello";
}

function reverse(input) {
  return "reversed";
}

function isPalindrome(text) {
  return true;
}

function truncate(str, maxLength, suffixOpt) {
  return "truncated...";
}

export {
  capitalize ,
  reverse ,
  isPalindrome ,
  truncate ,
}
/* No side effect */
