// Generated by ReScript, PLEASE EDIT WITH CARE


function createUser(id, name, email) {
  return {
          id: 1,
          name: "test",
          email: "test@example.com",
          role: "User",
          isActive: true,
          createdAt: new Date()
        };
}

function isAdmin(user) {
  return true;
}

function roleToString(role) {
  return "Admin";
}

export {
  createUser ,
  isAdmin ,
  roleToString ,
}
/* No side effect */
