// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Npm from "../src/Npm.res.mjs";
import * as Buntest from "bun:test";
import * as Core__Result from "@rescript/core/src/Core__Result.res.mjs";

Buntest.describe("Npm", (function () {
        Buntest.describe("fetchPackageDetails", (function () {
                Buntest.test("successfully fetches package details from npm", (async function () {
                        var result = await Npm.fetchPackageDetails("rescript");
                        Buntest.expect(result).toBeTruthy();
                        var result$1 = Core__Result.getExn(result);
                        Buntest.expect(result$1.name).toEqual("rescript");
                        Buntest.expect((function (x) {
                                    return x.dist.tarball;
                                  })(result$1.versions["11.0.0"])).toEqual("https://registry.npmjs.org/rescript/-/rescript-11.0.0.tgz");
                      }));
                Buntest.test("it handles cases where the npm module doesn't exist", (async function () {
                        var result = await Npm.fetchPackageDetails("4829104859_58393-$#@@");
                        Buntest.expect(result).toEqual({
                              TAG: "Error",
                              _0: "Not found"
                            });
                      }));
              }));
        Buntest.describe("getLatestVersion", (function () {
                Buntest.test("it returns the latest version", (async function () {
                        var details = await Npm.fetchPackageDetails("rescript").then(Core__Result.getExn);
                        Buntest.expect(Npm.getLatestVersion(details)).toBeTruthy();
                      }));
              }));
      }));

export {
  
}
/*  Not a pure module */
