// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Handlers$ResX from "rescript-x/src/Handlers.res.mjs";

var handler = Handlers$ResX.make((async function (_request) {
        return {
                userId: undefined
              };
      }), undefined);

function useContext() {
  return Handlers$ResX.useContext(handler);
}

export {
  handler ,
  useContext ,
}
/* handler Not a pure module */
