// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hjsx$ResX from "rescript-x/src/Hjsx.res.mjs";

function Layout$Html(props) {
  return Hjsx$ResX.Elements.jsxs("html", {
              children: [
                Hjsx$ResX.Elements.jsx("head", {
                      children: Hjsx$ResX.Elements.jsx("title", {
                            children: "Test App"
                          })
                    }),
                Hjsx$ResX.Elements.jsx("body", {
                      children: props.children
                    })
              ]
            });
}

var Html = {
  make: Layout$Html
};

export {
  Html ,
}
/* Hjsx-ResX Not a pure module */
