// Generated by ReScript, PLEASE EDIT WITH CARE


console.log("DocServer starting...");

function main() {
  console.log("Hello from DocServer!");
}

console.log("Hello from DocServer!");

export {
  main ,
}
/*  Not a pure module */
